create table if not exists public.drive_links (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  category text not null default 'อื่นๆ',
  description text default '',
  created_at timestamptz not null default now()
);

alter table public.drive_links enable row level security;

drop policy if exists "public read drive links" on public.drive_links;
create policy "public read drive links"
on public.drive_links for select
to anon
using (true);

drop policy if exists "public insert drive links" on public.drive_links;
create policy "public insert drive links"
on public.drive_links for insert
to anon
with check (
  char_length(title) between 1 and 200
  and char_length(url) between 8 and 2000
  and url ~ '^https?://'
);

drop policy if exists "public delete drive links" on public.drive_links;
create policy "public delete drive links"
on public.drive_links for delete
to anon
using (true);

create index if not exists drive_links_created_at_idx
on public.drive_links (created_at desc);
